springdoc:
  api-docs:
    enabled: true
  show-actuator: true
---
spring:
  profiles:
    default: local
  application:
    name: imagengine
  docker:
    compose:
      enabled: true
      file: ./src/main/docker/services.yml
      lifecycle-management: start-only
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    cors:
      allowed-methods: '*'
      allowed-headers: '*'
      allowed-origins: '*'
    schema:
      locations: classpath:schema/**/
  webflux:
    problemdetails:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        registration:
          oidc:
            client-id: 522456515438-an6u0ohgg8u5geh5mbcm2i5i40n5og7i.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
      resourceserver:
        jwt:
          authority-prefix: ''
          authorities-claim-name: auth
---
mongock:
  migration-scan-package:
    - solutions.onz.services.imagengine.dbmigrations
---
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - logfile
          - loggers
          - prometheus
          - threaddump
  endpoint:
    health:
      show-details: always
      #roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false
    mongo:
      enabled: false
    redis:
      enabled: true
  observations:
    key-values:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true

    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    data:
      repository:
        autotime:
          enabled: true
    tags:
      application: ${spring.application.name}

