spring:
  data:
    mongodb:
      auto-index-creation: true
  mail:
    host: localhost
    port: 25
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    cors:
      allowed-methods: '*'
      allowed-headers: '*'
      allowed-origins: '*'
    schema:
      locations: classpath:schema/**/