spring:
  mail:
    host: localhost
    port: 25
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    cors:
      allowed-methods: '*'
      allowed-headers: '*'
      allowed-origins: '*'
    schema:
      locations: classpath:schema/**/

imagengine:
  security:
    csp: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com; style-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com;"