name: imagengine
services:
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
  redis:
    extends:
      file: ./redis.yml
      service: redis
  prometheus:
    extends:
      service: prometheus
      file: ./monitoring.yml
  grafana:
    extends:
      service: grafana
      file: ./monitoring.yml