type Query {
    transform(input: TransformerInput!): TransformResult
    convert(input: ConverterInput!): ConverterResult
    histogram(input: SourceInput!): [HistogramResult]
    search(input: SearchInput!): SearchResult
}

input TransformerInput {
    from: FromInput!
    to: ToInput!
}

input ConverterInput {
    from: SourceInput!
    to: ToInput!
}

input SearchInput {
    what: WhatInput!
    where: WhereInput!
}

input WhatInput {
    object: String!
    probability: Float
}

input WhereInput {
    image: String!
}

input FromInput {
    image: String!
    resize: ResizeInput
    crop: CropInput
    rotate: RotateInput
    stitch: StitchInput
    sticker: StickerInput
    grayscale: Boolean
    sepia: Boolean
    cumulativeSink: Boolean
}

input SourceInput {
    images: [String!]!
}

input ResizeInput {
    width: Int!
    height: Int!
    sink: Boolean
    order: Int!
}

input CropInput {
    x: Int!
    y: Int!
    width: Int!
    height: Int!
    order: Int!
}

input RotateInput {
    angle: Int!
    order: Int!
}

input StitchInput {
    images: [String!]!
    direction: StitchDirection!
    order: Int!
}

enum StitchDirection {
    HORIZONTAL
    VERTICAL
}

input StickerInput {
    image: String!
    x: Int
    y: Int
    width: Int
    height: Int
    order: Int!
}

input ToInput {
    format: Format!
    quality: Int
}

type TransformResult {
    success: Boolean!
    message: String
    url: String
}

type ConverterResult {
    success: Boolean!
    message: String
    urls: [String]
}

type HistogramResult {
    image: String!
    histogram: [Int!]!
    url: String!
}

type SearchResult {
    success: Boolean!
    message: String
    markedImage: String
    coordinates: [PlanarCoordinates]
}

type PlanarCoordinates {
    x: Int!
    y: Int!
}

enum Format {
    JPEG
    PNG
    WEBP
}